### ISSUE TITLE
Empty logs

### ISSUE THREAD

**Issue by clin99** [hobbit-project/DEBS-GC-2018#25] opened 2018-04-23 01:08 UTC
I run the experiment on the Hobbit platform and the resulting Benchmark and System logs are ```[]```. Can you look into this?

Thanks.

**Comment by clin99** [comment] 2018-04-24 05:14
Can the organizers look into this please?     The log is important for debugging our System.

Thanks.

**Comment by MichaelRoeder** [comment] 2018-04-24 08:03
If the logs are empty, it typically means that there are no logs available.

Please provide some more information since we can not start checking all the possible of logs of all systems ;)
We need
- the URI of your system or your image name(s)
- the URI or ID of an experiment for which you would like to have logs

**Comment by smirnp** [comment] 2018-04-24 09:09
It stopped provide logs at least for my [dummy system adapter](https://master.project-hobbit.eu/experiments/1524491594093). Previously logs of the benchmark and system adapter looked like [this](https://master.project-hobbit.eu/experiments/1522853843090)

**Comment by clin99** [comment] 2018-04-25 19:55
@MichaelRoeder  The image name is mtdetector and the ID of experiment is 1524679274593.

**Comment by MichaelRoeder** [comment] 2018-04-26 08:34
We identified the problem and it should be fixed, soon. (https://github.com/hobbit-project/platform/issues/271#issuecomment-384558913)

**Comment by smirnp** [comment] 2018-05-01 10:08
@MichaelRoeder , are there any updates? 
The problem is very critical, since the benchmark with the acknowledgement mechanism does not working stable in the online platform (while works well on a single node instance) and we are on the finishing week of systems submission deadline.

**Comment by MichaelRoeder** [comment] 2018-05-01 10:39
We have implemented a fix but not all tests have been finished until now.
We have public holidays, today. I hope that I can give you an update, tomorrow.

**Closed as completed** 2018-11-30 14:14 UTC
