### ISSUE TITLE
Online platform execution

### ISSUE THREAD

**Issue by clin99** [hobbit-project/DEBS-GC-2018#28] opened 2018-04-24 22:35 UTC
Does the Benchmark send a termination message to the System when all tuples are sent?   If this is not true, how does our system know that all tuples are sent and when to terminate?    

Thanks.

**Comment by smirnp** [comment] 2018-04-25 07:07
Hi! The platform itself sends a task generation finished command (byte=15) and after receiving that systemAdapter terminates itself. You may look at the implementation of it in [python](https://github.com/hobbit-project/python-sample-system/blob/255c75cae57f2aa559879be0c9b204606aebdec8/src/main/supplementary/AbstractSystemAdapter.py#L77)

**Comment by clin99** [comment] 2018-04-25 22:13
@smirnp  Does the hobbit platform send the task generation finished command (byte=15) after the evaluation module has received all predictions? Or it sends the task generation finished command right after the last tuple. We want to terminate our program safely without missing the last tuple.

Suppose there is only ***one*** tuple, can you confirm which one of the following is correct?

1. You generate/send the tuple -> We send the prediction -> You receive the prediction and send the task generation finished command -> We shut down our system

2. You generate/send the tuple. Because this is the last tuple, you immediately send the task generation finished command -> If this task generation command comes first then we shut down our system, leaving one tuple unhandled.

Because there is no way to know the exact number of tuples to receive with during the runtime, we need to ensure our system terminates properly.

**Comment by smirnp** [comment] 2018-04-26 07:09
> Or it sends the task generation finished command right after the last tuple. We want to terminate our program safely without missing the last tuple.

After receiving the `task generation finished` signal the system might be terminated only if the taskGen2System queue is empty (all tuples were extracted by system). You have to implement such a control in your system. 

I just realized, that in python code this requirement was not implemented (in Java it is implemented as described).

**Comment by acip** [comment] 2018-04-26 08:26
Pavel, we may have missed it, can you point to the python system adapter
example?

**Comment by smirnp** [comment] 2018-04-26 09:54
Please find it in #5.

**Comment by clin99** [comment] 2018-04-26 13:58
@smirnp   Does the task generator terminate after it confirms **all predictions** have been received by the evaluation module?        Or does the task generator terminate immediately right after it sends the last task?

**Comment by smirnp** [comment] 2018-04-26 14:43
@clin99 , now the signal will be sent after all tasks were sent out to the queue. 
I will modify it to send a termination signal only after all the messages will be received by a storage. 
Do you already faced with the problem in online benchmark?

**Comment by clin99** [comment] 2018-04-26 15:29
@smirnp 
Sometimes the online benchmarking gets stuck and we found an error message shown in the Benchmark log. I think this is because our System terminates before sending out the last prediction.    Could you check the experiment 1524754187446?

**Comment by tsung-wei-huang** [comment] 2018-04-26 16:04
@smirnp We are concerned about this because we use two threads to monitor the `command queue` and `task queue`. If the master thread receives the `task generation finished` signal, according to your  description, it ***cannot*** immediately terminate the program because the other thread has to wait until the last data is extracted from the queue. Unfortunately, there is no way to know whether we are extracting the last data because the tuple might arrive before or after the `task generation finished` signal.

To make this simple, could you please either add an environment variable for the total number of tuples to process or send `task generation finished` only if you receive all predictions so we can terminate our program correctly.

I suspect your Python implementation also faces this issue.

**Comment by tsung-wei-huang** [comment] 2018-04-29 17:59
@smirnp  Any update? Thanks for your hard work.

**Comment by acip** [comment] 2018-04-30 17:28
Hi @smirnp, 

Lately our system, using the Java SystemAdapter provided as template does not seem to ever terminate. I see others are having similar issues in results section. Is the current system  (benchmark) stable or can you confirm that we should recheck our system or please check the benchmark?

Note: our recent changes might not impact termination and even if we rolled back to later version, the outcome is the same - experiment runs until timeout.

Thank you for your hard work! Clock is ticking and we are all connected :)

All the best,
Ciprian

**Comment by tsung-wei-huang** [comment] 2018-04-30 17:37
@acip 

I guess you ran into a similar situation as us. There is no way for us to know when all tuples are sent. Getting the `task generation finished` signal only tells us all tuples are sent, but we still don't not know how many tuples to extract from the queue. If we terminate our program after receiving this signal, there may still be some tuples on their way. Unfortunately, tuples and this signal are sent through different queues, command queue and task queue, making it impossible to develop a correct handshaking considering the network delay. 

I think the best solution is to modify the benchmark system and make sure once `task generation finished` signal is sent, we can properly terminate our system (process).

**Comment by smirnp** [comment] 2018-04-30 19:22
@acip, currently I see the bug, that benchmark hangs up with the limit!=0. Fixing it

**Comment by acip** [comment] 2018-04-30 19:24
Cool! :) Looks like happening for limit=0, also. Just released the platform
for you :)

**Comment by tsung-wei-huang** [comment] 2018-05-01 04:59
@smirnp 

Have you figured out how we can to stop the program properly? If we can't rely on `task generation finished` signal, what can we do? Really frustrated with this. We built our system using C++ on top of `amqp` C API. We also found using `amqp_consume_message` with a given timeout will cause our system to hang during benchmarking process. 

Can you add a field to `SYSTEM_PARAMETERS_MODEL` denoting the number of queries to send?  This will resolve all the troubles we are facing now.

**Comment by smirnp** [comment] 2018-05-01 09:52
Hi @twhuang-uiuc! 
Currently I'm preparing a new benchmark images, where taskGenerator will be terminated only after all responses will be received by evalStorage. So the `task generation finished` will be sent only after that.

**Comment by smirnp** [comment] 2018-05-01 10:03
@clin99, @acip, I'm checking the problem at the moment. The most probably benchmark hangs up because the `evalStorage` does not receive all the required tuples from a system (this might be a network delays or or sendout failures or whatever else) and not notifies taskGenerator to continue some of the ships. I see the problem even on a dummySystemAdapter, which does no processing at all. 

Since the online platform has no logs last week (even inside backend), I'm truying to reproduce the problem on a local instance of it (not a cluster), as well to setup benchmark logging into an external source. Any further updates will be ASAP.

**Comment by tsung-wei-huang** [comment] 2018-05-01 13:56
@smirnp  Thanks for your hard work! Yes, we agree sending `task finished signal` after the ***evaluation has processed all the prediction***. This way, we can safely terminate our program and no need for complex handshaking controls. Please keep us posted.

**Comment by smirnp** [comment] 2018-05-01 18:31
The hanging-up problem is fixed. 
A number of evaluated tuples from run to run may differ a little. Currently fixing it.

**Comment by smirnp** [comment] 2018-05-02 17:54
Dear all, currently the benchmark still have hang-up problem. 
Please stop execution manually if is not finishing during 2-3 minutes. 
I'm fixing it at the moment.

**Comment by smirnp** [comment] 2018-05-02 18:01
Now it is fixed. Sorry for inconveniences.

**Comment by smirnp** [comment] 2018-05-02 21:15
Please use the timeout field. From now it is applied for the whole benchmark, not for task generator only. In logs I see lots of system initialization errors and such runs proceed until the platform timeout.

**Comment by tsung-wei-huang** [comment] 2018-05-02 21:22
@smirnp Thanks for the hard work. Just wanna confirm. Now the `task generation finished` signal will be sent ***only after*** your benchmark system has processed all required predictions we send, right?

**Comment by smirnp** [comment] 2018-05-03 08:20
@twhuang-uiuc , yes. Now `task generation finished` will be sent out only after all notifications about received predictions were received from the storage.

**Comment by smirnp** [comment] 2018-05-03 08:33
@all, I have fixed some more troubles with the benchmark last night. At least three systems have been tested last evening/night are seemed to be correctly finishing now. 

For those, who builds their image via provided Java code - please update repo to the latest version (updated to SDK 1.1.7). It uses improved ComponentStarter class (specified in dynamically generated docker files), which stably terminates containers after java code inside finishes. Initial class (taken from the standard HOBBIT library) seems to be unstable in containers termination, which lead to hang ups.

Please, try to avoid logging of every message receive event or do that on a limited amount of tuples. Otherwise log file will include 25K messages and will not be available for download.

**Comment by clin99** [comment] 2018-05-03 23:06
@smirnp  I receive `The benchmark terminated with an error.` message in some experiments and sometimes the experiments will get stuck in evaluation phase.  Could you please look into this?     The experiment ID are 1525387738744 and 1525387736239.

Thanks.

**Comment by smirnp** [comment] 2018-05-04 13:36
@MichaelRoeder , can you please have a look? The benchmark finished correctly, the result model is correctly displayed, but it is labeled as an erroneous in the GUI

**Comment by rivetti** [comment] 2018-05-05 12:53
@smirnp 
Dear Pavel,
I am consistently hitting a timeout error:
[org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <Timeout reached. Stopping benchmark>

From the logs inspection it seems that the system does output all tuples:
 <Actuals: 2000 (0) t/s) Expectations: 2000 (0 t/s)>

and I am positive the jvm shutdowns. Just to be sure, in the last run I added a brutal System.exit() after receiving the task generation finished signal.

Do you have some insight? (experiment 1525516861065)

Thanks
Bests

**Comment by acip** [comment] 2018-05-05 15:29
Benchmark is stalling at "The task generation has ended and the benchmark is evaluating."

Ref: https://master.project-hobbit.eu/experiments/1525533372112

**Comment by tsung-wei-huang** [comment] 2018-05-05 15:48
Yes. We also run into this problem occasionally. Not sure what happen.

**Comment by smirnp** [comment] 2018-05-07 08:28
@rivetti , @acip , @twhuang-uiuc , yes the problem with benchmark hanging still exists, while it occurs occasionally - benchmark containers are not exiting after jvm inside them is finished.

I have applied some fix and now trying to check your systems. In any case register them for the challenge, since they are already in the platform.

**Comment by smirnp** [comment] 2018-05-07 12:54
@rivetti , I have checked your system - the system's container still remain unclosed after the execution. Only when I drop it manually benchmark proceeds further. I have fixed fully the same problem with a benchmark last week: system adapter seems to be finished, but container continued its work. 

Do you use the standard `org.hobbit.core.run.ComponentStarter` class in your Docker File? If yes, then use [the fixed one](https://github.com/hobbit-project/java-sdk/blob/master/src/main/java/org/hobbit/sdk/utils/ComponentStarter.java) instead.

**Comment by smirnp** [comment] 2018-05-07 13:15
@twhuang-uiuc , could you please provide me with the name of your system? 
It seems there are no problems at benchmark side

**Comment by clin99** [comment] 2018-05-07 13:25
@smirnp   The name of the System is mtdetector and the experiment ID are 1525387738744 and 1525387736239.

**Comment by MichaelRoeder** [comment] 2018-05-07 14:29
@clin99 for both examples, I can not see a real problem. The benchmark seems to terminate in a correct way and apart from the error message, the results on the page are the results as the benchmark is measuring them. :thinking:

**Comment by smirnp** [comment] 2018-05-07 14:34
@clin99 , @MichaelRoeder , there is an occasional problem (non-unique taskIds, but is not expected since the online images are single threaded now). I'm fixing it at the moment. 
Apart of that containers might not exit probably because of [this](https://github.com/hobbit-project/core/issues/21) - I saw it for benchmark components and see on @rivetti 's system when checking it at my instance of the platform.

**Comment by rivetti** [comment] 2018-05-07 14:36
@smirnp 
Dear Pavel,
I run again our system with the linked ComponentStarter.
Here is the link to the experiment: https://master.project-hobbit.eu/experiments/1525701249524
Do I get everything went smoothly?

**Comment by smirnp** [comment] 2018-05-07 14:37
@MichaelRoeder , sorry just noticed that you are talking about this https://github.com/hobbit-project/DEBS-GC-2018/issues/28#issuecomment-386603430  . Yes, it seems strange

**Closed as completed** 2018-11-30 14:14 UTC
Labels: discussion
